"""Initial migration

Revision ID: 20251006_121412
Revises: 
Create Date: 2025-10-06 12:14:12.325066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20251006_121412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('unique_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_alias', sa.String(length=50), nullable=False),
    sa.Column('g_node_alias', sa.String(length=100), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('primary_contact', sa.JSON(), nullable=False),
    sa.Column('secondary_contact', sa.JSON(), nullable=True),
    sa.Column('hardware_layout', sa.JSON(), nullable=True),
    sa.Column('alert_status', sa.JSON(), nullable=False),
    sa.Column('representation_status', sa.JSON(), nullable=True),
    sa.Column('scada_ip_address', sa.String(length=45), nullable=True),
    sa.Column('scada_git_commit', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('g_node_alias'),
    sa.UniqueConstraint('short_alias')
    )
    
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    
    op.create_table('hourly_electricity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_node_alias', sa.String(length=100), nullable=False),
    sa.Column('short_alias', sa.String(length=50), nullable=False),
    sa.Column('hour_start_s', sa.Integer(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('energy_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('g_node_alias', sa.String(length=100), nullable=False),
    sa.Column('short_alias', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_logs')
    op.drop_table('energy_data')
    op.drop_table('hourly_electricity')
    op.drop_table('users')
    op.drop_table('homes')
    # ### end Alembic commands ###
