"""Add last_login column to users table

Revision ID: d825f3862ef7
Revises: 20251006_121412
Create Date: 2025-10-07 10:42:30.763068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd825f3862ef7'
down_revision: Union[str, None] = '20251006_121412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('homes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'homes', ['short_alias'])
    op.create_unique_constraint(None, 'homes', ['g_node_alias'])
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_constraint(None, 'homes', type_='unique')
    op.drop_constraint(None, 'homes', type_='unique')
    op.drop_column('homes', 'updated_at')
    op.drop_column('homes', 'created_at')
    # ### end Alembic commands ###
